// products
export const GET_PRODUCT_CHAIRS = "GET_PRODUCT_CHAIRS";
export const GET_PRODUCT_TABLES = "GET_PRODUCT_TABLES";
export const GET_PRODUCT_OTHER_EQUIPMENTS = "GET_PRODUCT_OTHER_EQUIPMENTS";

// cart
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_ON_CART = "UPDATE_ON_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

// login
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
